## Create arrays with all the data types available in numpy
Available data types in munpy

- integer
- boolean
- unsigned integer
- float
- complex float
- timedelta
- datetime
- object
- string
- unicode string
- void

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a, a.dtype)

[1 2 3 4 5] int32


In [3]:
b = np.array([1,2,3,0,0,4], dtype='bool_')
print(b, b.dtype)

[ True  True  True False False  True] bool


In [4]:
c = np.array([0,2,1,4,3,6], dtype='uint32')
print(c,c.dtype)

[0 2 1 4 3 6] uint32


In [5]:
d = np.array([1,2,3,4,5,6], dtype='float32')
print(d,d.dtype)

[1. 2. 3. 4. 5. 6.] float32


In [6]:
e = np.array([1,2,3,4,5,6], dtype='complex_')
print(e,e.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j] complex128


In [7]:
f = np.timedelta64(1,'D')
print(f,f.dtype)

1 days timedelta64[D]


In [8]:
g = np.array(['2002-05-15','2009-07-16','2004-03-20'], dtype='datetime64')
print(g,g.dtype)

['2002-05-15' '2009-07-16' '2004-03-20'] datetime64[D]
